---
- hosts: all
  become: true
  tasks:
    - name: dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: gpg keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: check if active
      service:
        name: docker
        state: started
        enabled: yes
    - name: clone git repo
      git:
        repo: https://github.com/JakubSamulski/Chmury.git
        dest: /home/Chmury
        clone: yes
        update: yes
    - name: write .env file
      copy:
        content: |
          VITE_IP="{{ ansible_ssh_host }}"
        dest: /home/Chmury/.env
    - name: write client .env file
      copy:
        content: |
          VITE_IP="{{ ansible_ssh_host }}"
        dest: /home/Chmury/Client/.env
    - name: run docker-compose
      command: docker compose up -d
      args:
        chdir: /home/Chmury